"""initial tables

Revision ID: 16083a9995d7
Revises: 
Create Date: 2026-08-30 21:28:56.869679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16083a9995d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('starting_stack', sa.Integer(), nullable=False),
    sa.Column('ante_mode', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('players_count', sa.Integer(), nullable=False),
    sa.Column('blind_level_minutes', sa.Integer(), nullable=False),
    sa.Column('starting_small_blind', sa.Integer(), nullable=False),
    sa.Column('starting_big_blind', sa.Integer(), nullable=False),
    sa.Column('payouts', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('seat', sa.Integer(), nullable=False),
    sa.Column('is_human', sa.Boolean(), nullable=False),
    sa.Column('personality', sa.String(length=40), nullable=True),
    sa.Column('starting_stack', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poker_hands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('hand_number', sa.Integer(), nullable=False),
    sa.Column('hero_seat', sa.Integer(), nullable=False),
    sa.Column('hero_position', sa.String(length=10), nullable=False),
    sa.Column('blind_level', sa.String(length=20), nullable=False),
    sa.Column('community_cards', sa.JSON(), nullable=False),
    sa.Column('starting_stacks', sa.JSON(), nullable=False),
    sa.Column('ending_stacks', sa.JSON(), nullable=False),
    sa.Column('pot_total', sa.Integer(), nullable=False),
    sa.Column('winner_seats', sa.JSON(), nullable=False),
    sa.Column('tournament_stage', sa.String(length=30), nullable=False),
    sa.Column('icm_pressure', sa.String(length=20), nullable=False),
    sa.Column('hero_cards', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('hands_played', sa.Integer(), nullable=False),
    sa.Column('hands_won', sa.Integer(), nullable=False),
    sa.Column('vpip', sa.Float(), nullable=False),
    sa.Column('pfr', sa.Float(), nullable=False),
    sa.Column('coach_agreement', sa.Float(), nullable=False),
    sa.Column('icm_mistakes', sa.Integer(), nullable=False),
    sa.Column('chip_profit', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coach_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hand_id', sa.Integer(), nullable=False),
    sa.Column('recommended_action', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.String(length=500), nullable=False),
    sa.Column('alternative_action', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['hand_id'], ['poker_hands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hand_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hand_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('seat', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('street', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['hand_id'], ['poker_hands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hand_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hand_id', sa.Integer(), nullable=False),
    sa.Column('main_winner_seat', sa.Integer(), nullable=False),
    sa.Column('amounts', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['hand_id'], ['poker_hands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opponent_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('vpip', sa.Float(), nullable=False),
    sa.Column('pfr', sa.Float(), nullable=False),
    sa.Column('three_bet', sa.Float(), nullable=False),
    sa.Column('aggression', sa.Float(), nullable=False),
    sa.Column('bluff', sa.Float(), nullable=False),
    sa.Column('call_tendency', sa.Float(), nullable=False),
    sa.Column('fold_tendency', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hand_id', sa.Integer(), nullable=False),
    sa.Column('hero_action', sa.String(length=20), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['hand_id'], ['poker_hands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy_decisions')
    op.drop_table('opponent_profiles')
    op.drop_table('hand_results')
    op.drop_table('hand_actions')
    op.drop_table('coach_recommendations')
    op.drop_table('session_statistics')
    op.drop_table('poker_hands')
    op.drop_table('players')
    op.drop_table('tournament_configurations')
    op.drop_table('sessions')
    op.drop_table('tournaments')
    # ### end Alembic commands ###
